### PR TITLE
Added HashMap implementation for custom Fields and updated Unit Tests

### PR DESCRIPTION
**Pull request by varundhall**
Few fundamental fields written below were not available:
 - PlatformMaker
 - RenderingEngine
 - RenderingEngineMaker
 - RenderingEngineVersion

These fields are important and often required while parsing the user agents to get deeper insights.

This PR adds these 4 new fields, also the existing unit tests are modified to comply with the changes. Documentation is also updated for reference.

### CODE REVIEW

**Comment by paulrutter** [comment]
Hi @varundhall,

Thanks for your pull request. I will take a thorough look in the upcoming days.
On a first glance however, i'm not sure we want to move down this path. The library is currently very low on memory, partly because we do not store all available fields in memory.

I guess the list of fields one would like to have very much differs from the usecase. That's why i would rather move to a configuration based solution, where one can configure what fields to load. That way, all usecases can be supported without having to change the library again.

Yes, that would take some effort to implement, but it would be more future proof, i guess.

**Comment by varundhall** [comment]
@paulrutter I totally see where that's coming from.

I can implement a way in which we can pass a List of Strings (fields) while loading the parser and then return a HashMap object while parsing user-agents string via Capabilities object.

**Comment by paulrutter** [comment]
Yes, that is exactly what i'm thinking of (see the README, Future paragraph: "Make the fields configurable and let Capabilities return a Map containing the given fields").
To keep it backwards compatible, the default fields should be the ones already available now:

browser (e.g. Chrome)
browserType (e.g. Browser or Application)
browserMajorVersion (e.g. 61 in case of Chrome)
deviceType (e.g. Mobile Phone, Desktop, Tablet, Console, TV Device)
platform (e.g. Android, iOS, Win7, Win8, Win10)
platformVersion

Looking forward to your updated PR; it would be a nice improvement to the library!

**Comment by paulrutter** [comment]
Thanks for your swift work @varundhall , i'll take a look at this today 👍

**Comment by varundhall** [comment]
@paulrutter I just have to update the documentation (README.md) and I'm working on it right now.

Also I see that the library has good coverage please try to add the code-coverage label in ReadMe.md via https://coveralls.io/ if possible

**Comment by paulrutter** [comment]
Ok, i do have some small changes to make, but i'll do that myself while reviewing the code.
Looking good overall!

I'll add code coverage later, thanks for the tip.

**Comment by varundhall** [comment]
@paulrutter Should I update the readme or you'll do it yourself?

Also when I can expect a release of this change. I have to use it in some project and since its listed in maven central repo, it will be pretty easy for me to directly add a dependency to your existing project instead of maintain my fork.

**Comment by paulrutter** [comment]
I'll update the readme myself and will try to release today (if all is well).

**Comment by varundhall** [comment]
Thanks @paulrutter I'm looking forward for a release.
Cheers!

**Comment by paulrutter** [comment]
Let's continue in https://github.com/blueconic/browscap-java/pull/3

**Pull request closed without merging**
