### PR TITLE
Update README.md by adding a link to repository map

### PR DESCRIPTION
**Pull request by alexkarezin**
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/blueconicbrowscapjava/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.

In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

### CODE REVIEW

**Comment by alexkarezin** [comment]
@paulrutter 
Paul, any chance you can take a look? I'm wondering if you see this being useful and how can it be improved. Thanks!

**Comment by paulrutter** [comment]
Hi @alexkarezin,

Can you elaborate a bit on what you're trying to achieve?
The diagrams look useful at first sight.

And what about licensing, how is your project licensed?

**Comment by alexkarezin** [comment]
Hey @paulrutter, the goal of the project is to provide (and automatically maintain) an easy-to-undersand visual representation of BrowsCap internals. 

Specifically:

For BrowsCap contributors, the diagrams provide an interactive introduction to the project structure (which contirbutors need to understand before they get their hands 'dirty').

For BrowsCap users, the diagrams provide a piece of mind of knowing what comes into solution they are integrating with (I guess we all want to know what's inside even if we are not planning to change it).

The documentation engine is a project that me and my partner support and maintain. It has been used by numerous GH projects. The documentation itself can be licensed under MIT/Apache2/... BrowsCap maintainer's preference. I would assume MIT would suite best. 

Hope this helps, let me know if I can provide more clarity.
Thank you!

**Comment by paulrutter** [comment]
I merged it in, thanks for the PR.

**Pull request merged**
