### PR TITLE
Add resource-config.json for GraalVM Native Image support

### PR DESCRIPTION
**Pull request by izeye**
This PR adds `resource-config.json` for GraalVM Native Image support.

### CODE REVIEW

**Comment by paulrutter** [comment]
@izeye can you elaborate on what this PR does?
And update the readme and changelog with instructions on how to use it?

**Comment by izeye** [comment]
@paulrutter Sorry for the lack of details.

This PR tries to support GraalVM Native Image by [providing metadata for resources](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#resource-metadata-in-json) (ie. `browscap-xxx.zip`).

I tried to illustrate the difference between with and without the file with the following samples: [`native-image` branch](https://github.com/izeye/hello-browscap-java/tree/native-image) and [`native-image-with-resource-config-json` branch](https://github.com/izeye/hello-browscap-java/tree/native-image-with-resource-config-json)

Please see their `README.md` files.

I also updated the `README.md` and the `CHANGELOG.txt` as you requested.

Please let me know if there's anything else I need to do.

**Comment by paulrutter** [comment]
Thanks, i'll try to merge it next week and release it as 1.4.0.

**Comment by paulrutter** [comment]
If i understand correctly, you could also fix it by using an alternative constructor where you feed in the browscap zip yourself: ` public UserAgentService(final String zipFilePath) {`

**Comment by paulrutter** [comment]
Released as version 1.4.0, pushing into sonatype now.

**Pull request merged**
