### PR TITLE
Improved parser initiating

### PR DESCRIPTION
**Pull request by hacker13ua**
I investigated slow startup described in #30 and found out that if change csv parser library then in local environment i can reduce startup time from 12 seconds to 8

### CODE REVIEW

**Comment by paulrutter** [comment]
@arthurmeijer what do you think of this PR? Another CSV library is used.

**Comment by arthurmeijer** [comment]
Univocity-parsers are released under Apache 2.0 license, so the same as commons-csv.
The code changes are fine and the performance gain is impressive.

**Comment by paulrutter** [comment]
Ok thanks for the feedback.
I'll merge the PR soon and release a new version :)

Thanks @hacker13ua!

**Comment by paulrutter** [comment]
Published as 1.3.0.

**Pull request merged**
